MODEL:
  WEIGHT: "imagenet"
  FREEZE: False
  VISUAL_MODEL: "m_resnet"
  TEXTUAL_MODEL: "bigru"
  NUM_CLASSES: 11003
  NUM_PARTS: 5
  GRU:
    ONEHOT: "clip_vit"
    EMBEDDING_SIZE: 512
    NUM_UNITS: 512
    VOCABULARY_SIZE: 512
    DROPOUT_KEEP_PROB: 1.0
    MAX_LENGTH: 100
    CUT_NEG: True
  RESNET:
    RES5_STRIDE: 1
  EMBEDDING:
    EMBED_HEAD: 'cutneg'
    FEATURE_SIZE: 256
    DROPOUT_PROB: 0.0
    EPSILON: 0.1
INPUT:
  HEIGHT: 384
  WIDTH: 128
  USE_AUG: True
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
DATASETS:
  TRAIN: ("cuhkpedes_train", )
  TEST: ("cuhkpedes_test", )
  USE_SEG: FALSE
  USE_ATT: FALSE
SOLVER:
  IMS_PER_BATCH: 64
  NUM_EPOCHS: 80
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.00004
  CHECKPOINT_PERIOD: 40
  LRSCHEDULER: 'step'
  STEPS: (40, 70)
  WARMUP_FACTOR: 0.1
  WARMUP_EPOCHS: 5
TEST:
  IMS_PER_BATCH: 64
