MODEL:
  WEIGHT: "imagenet"
  FREEZE: False
  VISUAL_MODEL: "resnet101"
  TEXTUAL_MODEL: "bert"
  EMBEDDING:
    EMBED_HEAD: 'triplet'
    FEATURE_SIZE: 256
    DROPOUT_PROB: 0.0
    EPSILON: 0.1
INPUT:
  HEIGHT: 224
  WIDTH: 224
  USE_AUG: True
DATASETS:
  TRAIN: ("mscoco_train", "mscoco_rv")
  TEST: ("mscoco_test", )
  USE_ATT: False
DATALOADER:
  EN_SAMPLER: False
SOLVER:
  IMS_PER_BATCH: 128
  NUM_EPOCHS: 30
  BASE_LR: 0.00001
  WEIGHT_DECAY: 0.00004
  CHECKPOINT_PERIOD: 15
  LRSCHEDULER: 'step'
  STEPS: (15, 30)
  WARMUP_FACTOR: 0.1
  WARMUP_EPOCHS: 0
TEST:
  IMS_PER_BATCH: 128
